export let FETCH_LIST_PRODUCT = "FETCH_LIST_PRODUCT";
export let FETCH_DELETE_PRODUCT = "FETCH_DELETE_PRODUCT";
export let FETCH_EDIT_PRODUCT = "FETCH_EDIT_PRODUCT";
export let FETCH_UPDATE_PRODUCT = "FETCH_UPDATE_PRODUCT";
export let FETCH_SEARCH_PRODUCT = "FETCH_SEARCH_PRODUCT";
export let FETCH_FILTER_PRODUCT = "FETCH_FILTER_PRODUCT";
export let FETCH_SORT_PRODUCT = "FETCH_SORT_PRODUCT";